# Generated by Django 3.2.6 on 2021-12-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users_data',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mail_id', models.CharField(max_length=100)),
                ('phone_num', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
