# Generated by Django 3.2.6 on 2021-12-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_data',
            name='lang',
            field=models.CharField(default='eng', max_length=100),
            preserve_default=False,
        ),
    ]
